import { promises as fs } from 'fs'

import path from 'path'

const appRoot = process.cwd()
const srcDir = path.join(appRoot, 'src')
const libDir = path.join(srcDir, 'lib')            // <-- routeLoaders.tsx lives here

const searchRoots = [
  path.join(srcDir, 'pages'),
  path.join(srcDir, 'routes'),
  path.join(srcDir, 'views'),
  path.join(srcDir, 'components'),
  path.join(srcDir, 'sections'),
  path.join(appRoot, '..', '..', 'packages'),
  path.join(appRoot, '..', '..', 'components'),
].filter(Boolean)

const targets = [
  'Dashboard','Analytics','Export','Pricing','HowItWorks','HowItWorksPage','About',
  'QuickStart','TierDemo','Settings','Privacy','Contact','Developers','Signup'
]

async function exists(p:string){ try{ await fs.access(p); return true }catch{ return false } }

async function collect(): Promise<Record<string,string[]>> {
  const found: Record<string,string[]> = Object.fromEntries(targets.map(t => [t, []]))
  for (const root of searchRoots){
    if (!(await exists(root))) continue

    const stack = [root]
    while(stack.length){
      const dir = stack.pop()!
      const entries = await fs.readdir(dir, { withFileTypes:true })
      for (const e of entries){
        const p = path.join(dir, e.name)
        if (e.isDirectory()) { stack.push(p); continue }
        if (!/\.(tsx|ts|jsx|js)$/.test(e.name)) continue
        for (const t of targets){
          const base = `${t}.tsx`
          const base2 = `${t}.ts`
          const base3 = `${t}.jsx`
          const base4 = `${t}.js`
          const pageBase = `${t}Page.tsx`
          const pageBase2 = `${t}Page.ts`
          const pageBase3 = `${t}Page.jsx`
          const pageBase4 = `${t}Page.js`
          // Also check for PrivacyTermsPage for Privacy target
          const privacyTerms = t === 'Privacy' && e.name === 'PrivacyTermsPage.tsx'
          // Also check for DashboardTierDemo for TierDemo target
          const tierDemo = t === 'TierDemo' && e.name === 'DashboardTierDemo.tsx'
          
          if (e.name === base || e.name === base2 || e.name === base3 || e.name === base4 || 
              e.name === pageBase || e.name === pageBase2 || e.name === pageBase3 || e.name === pageBase4 ||
              privacyTerms || tierDemo) {
            // compute import path relative to libDir so imports work from src/lib/routeLoaders.tsx
            const relFromLib = path.relative(libDir, p).replace(/\\/g,'/').replace(/\.(tsx|ts|jsx|js)$/, '')
            // normalize to relative form starting with ./ or ../
            const importPath = relFromLib.startsWith('.') ? relFromLib : `./${relFromLib}`
            if (!found[t].includes(importPath)) found[t].push(importPath)
          }
        }
      }
    }
  }
  return found
}

function tpl(found: Record<string,string[]>) {
  const lines: string[] = []
  lines.push('// auto-generated by scripts/findPages.ts')
  lines.push('export const ROUTE_LOADERS: Record<string, Array<() => Promise<any>>> = {')
  for (const [name, arr] of Object.entries(found)) {
    const imports = arr.map(p => `() => import('${p}')`).join(', ')
    lines.push(`  "${name}": [${imports}],`)
  }
  lines.push('}')
  return lines.join('\n')
}

;(async () => {
  const found = await collect()
  await fs.mkdir(path.join(srcDir,'lib'), { recursive:true })
  await fs.writeFile(path.join(srcDir,'lib','routeLoaders.tsx'), tpl(found), 'utf8')

  const report: string[] = []
  report.push('--- Route wiring report ---')
  for (const [k, v] of Object.entries(found)){
    report.push(`${k}: ${v.length ? 'FOUND ' + v.length : 'MISSING'}`)
    v.forEach(p => report.push(`  - ${p}`))
  }
  await fs.writeFile(path.join(appRoot,'route-wiring.txt'), report.join('\n'), 'utf8')
  console.log(report.join('\n'))
})().catch(err => { console.error(err); process.exit(1) })
