// Hashtag to topic mapping for 500+ popular hashtags
// Used for quick topic identification from social media content

export interface HashtagMapping {
  hashtag: string;
  topic: string;
  popularity?: 'high' | 'medium' | 'low';
}

/**
 * 500+ popular hashtags mapped to topics
 * Hashtags are lowercase without # prefix
 */
export const HASHTAG_MAPPINGS: HashtagMapping[] = [
  // AI & Technology (50 hashtags)
  { hashtag: 'ai', topic: 'artificial_intelligence', popularity: 'high' },
  { hashtag: 'artificialintelligence', topic: 'artificial_intelligence', popularity: 'high' },
  { hashtag: 'machinelearning', topic: 'artificial_intelligence', popularity: 'high' },
  { hashtag: 'ml', topic: 'artificial_intelligence', popularity: 'medium' },
  { hashtag: 'deeplearning', topic: 'artificial_intelligence', popularity: 'medium' },
  { hashtag: 'neuralnetwork', topic: 'artificial_intelligence', popularity: 'low' },
  { hashtag: 'chatgpt', topic: 'artificial_intelligence', popularity: 'high' },
  { hashtag: 'gpt4', topic: 'artificial_intelligence', popularity: 'medium' },
  { hashtag: 'gpt', topic: 'artificial_intelligence', popularity: 'medium' },
  { hashtag: 'llm', topic: 'artificial_intelligence', popularity: 'low' },
  { hashtag: 'aiart', topic: 'artificial_intelligence', popularity: 'medium' },
  { hashtag: 'aitools', topic: 'artificial_intelligence', popularity: 'low' },
  { hashtag: 'generativeai', topic: 'artificial_intelligence', popularity: 'medium' },
  { hashtag: 'coding', topic: 'software_development', popularity: 'high' },
  { hashtag: 'programming', topic: 'software_development', popularity: 'high' },
  { hashtag: 'developer', topic: 'software_development', popularity: 'high' },
  { hashtag: 'webdev', topic: 'software_development', popularity: 'high' },
  { hashtag: 'javascript', topic: 'software_development', popularity: 'high' },
  { hashtag: 'python', topic: 'software_development', popularity: 'high' },
  { hashtag: 'reactjs', topic: 'software_development', popularity: 'medium' },
  { hashtag: 'nodejs', topic: 'software_development', popularity: 'medium' },
  { hashtag: 'github', topic: 'software_development', popularity: 'high' },
  { hashtag: 'opensource', topic: 'software_development', popularity: 'medium' },
  { hashtag: 'devlife', topic: 'software_development', popularity: 'low' },
  { hashtag: 'frontend', topic: 'software_development', popularity: 'medium' },
  { hashtag: 'backend', topic: 'software_development', popularity: 'medium' },
  { hashtag: 'fullstack', topic: 'software_development', popularity: 'medium' },
  { hashtag: 'tech', topic: 'gadgets_electronics', popularity: 'high' },
  { hashtag: 'technology', topic: 'gadgets_electronics', popularity: 'high' },
  { hashtag: 'gadgets', topic: 'gadgets_electronics', popularity: 'medium' },
  { hashtag: 'smartphone', topic: 'gadgets_electronics', popularity: 'medium' },
  { hashtag: 'iphone', topic: 'gadgets_electronics', popularity: 'high' },
  { hashtag: 'android', topic: 'gadgets_electronics', popularity: 'high' },
  { hashtag: 'laptop', topic: 'gadgets_electronics', popularity: 'medium' },
  { hashtag: 'electronics', topic: 'gadgets_electronics', popularity: 'medium' },
  { hashtag: 'techreview', topic: 'gadgets_electronics', popularity: 'low' },
  { hashtag: 'unboxing', topic: 'gadgets_electronics', popularity: 'medium' },
  { hashtag: 'crypto', topic: 'cryptocurrency', popularity: 'high' },
  { hashtag: 'cryptocurrency', topic: 'cryptocurrency', popularity: 'high' },
  { hashtag: 'bitcoin', topic: 'cryptocurrency', popularity: 'high' },
  { hashtag: 'btc', topic: 'cryptocurrency', popularity: 'high' },
  { hashtag: 'ethereum', topic: 'cryptocurrency', popularity: 'high' },
  { hashtag: 'eth', topic: 'cryptocurrency', popularity: 'high' },
  { hashtag: 'blockchain', topic: 'cryptocurrency', popularity: 'high' },
  { hashtag: 'nft', topic: 'cryptocurrency', popularity: 'high' },
  { hashtag: 'web3', topic: 'cryptocurrency', popularity: 'medium' },
  { hashtag: 'defi', topic: 'cryptocurrency', popularity: 'medium' },
  { hashtag: 'altcoin', topic: 'cryptocurrency', popularity: 'low' },
  { hashtag: 'hodl', topic: 'cryptocurrency', popularity: 'medium' },
  { hashtag: 'cryptotrading', topic: 'cryptocurrency', popularity: 'medium' },

  // Gaming (30 hashtags)
  { hashtag: 'gaming', topic: 'gaming', popularity: 'high' },
  { hashtag: 'gamer', topic: 'gaming', popularity: 'high' },
  { hashtag: 'videogames', topic: 'gaming', popularity: 'high' },
  { hashtag: 'esports', topic: 'gaming', popularity: 'high' },
  { hashtag: 'twitch', topic: 'gaming', popularity: 'high' },
  { hashtag: 'gamingcommunity', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'gameplay', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'pcgaming', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'consolegaming', topic: 'gaming', popularity: 'low' },
  { hashtag: 'streamer', topic: 'gaming', popularity: 'high' },
  { hashtag: 'gamingsetup', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'gaminglife', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'fortnite', topic: 'gaming', popularity: 'high' },
  { hashtag: 'minecraft', topic: 'gaming', popularity: 'high' },
  { hashtag: 'callofduty', topic: 'gaming', popularity: 'high' },
  { hashtag: 'cod', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'leagueoflegends', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'valorant', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'apexlegends', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'roblox', topic: 'gaming', popularity: 'high' },
  { hashtag: 'ps5', topic: 'gaming', popularity: 'high' },
  { hashtag: 'xbox', topic: 'gaming', popularity: 'high' },
  { hashtag: 'nintendo', topic: 'gaming', popularity: 'high' },
  { hashtag: 'switch', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'playstation', topic: 'gaming', popularity: 'high' },
  { hashtag: 'xboxseriesx', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'gamergirl', topic: 'gaming', popularity: 'medium' },
  { hashtag: 'gamerboy', topic: 'gaming', popularity: 'low' },
  { hashtag: 'gamersunite', topic: 'gaming', popularity: 'low' },
  { hashtag: 'twitchstreamer', topic: 'gaming', popularity: 'medium' },

  // Fitness & Health (40 hashtags)
  { hashtag: 'fitness', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'workout', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'exercise', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'gym', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'fitfam', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'training', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'gymlife', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'fitnessmotivation', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'gains', topic: 'fitness_exercise', popularity: 'medium' },
  { hashtag: 'cardio', topic: 'fitness_exercise', popularity: 'medium' },
  { hashtag: 'yoga', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'running', topic: 'fitness_exercise', popularity: 'high' },
  { hashtag: 'weightlifting', topic: 'fitness_exercise', popularity: 'medium' },
  { hashtag: 'bodybuilding', topic: 'fitness_exercise', popularity: 'medium' },
  { hashtag: 'crossfit', topic: 'fitness_exercise', popularity: 'medium' },
  { hashtag: 'nutrition', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'diet', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'healthyeating', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'mealprep', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'cleaneating', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'vegan', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'vegetarian', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'keto', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'paleo', topic: 'nutrition_diet', popularity: 'medium' },
  { hashtag: 'protein', topic: 'nutrition_diet', popularity: 'medium' },
  { hashtag: 'macros', topic: 'nutrition_diet', popularity: 'low' },
  { hashtag: 'mentalhealth', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'mentalhealthawareness', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'therapy', topic: 'mental_health', popularity: 'medium' },
  { hashtag: 'anxiety', topic: 'mental_health', popularity: 'medium' },
  { hashtag: 'depression', topic: 'mental_health', popularity: 'medium' },
  { hashtag: 'mindfulness', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'meditation', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'selfcare', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'wellness', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'mentalhealthmatters', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'health', topic: 'medical_health', popularity: 'high' },
  { hashtag: 'healthcare', topic: 'medical_health', popularity: 'medium' },
  { hashtag: 'healthylifestyle', topic: 'medical_health', popularity: 'high' },
  { hashtag: 'healthyliving', topic: 'medical_health', popularity: 'high' },

  // Business & Finance (40 hashtags)
  { hashtag: 'entrepreneur', topic: 'entrepreneurship', popularity: 'high' },
  { hashtag: 'entrepreneurship', topic: 'entrepreneurship', popularity: 'high' },
  { hashtag: 'startup', topic: 'entrepreneurship', popularity: 'high' },
  { hashtag: 'founder', topic: 'entrepreneurship', popularity: 'medium' },
  { hashtag: 'smallbusiness', topic: 'entrepreneurship', popularity: 'high' },
  { hashtag: 'sidehustle', topic: 'entrepreneurship', popularity: 'high' },
  { hashtag: 'businessowner', topic: 'entrepreneurship', popularity: 'medium' },
  { hashtag: 'startuplife', topic: 'entrepreneurship', popularity: 'medium' },
  { hashtag: 'solopreneur', topic: 'entrepreneurship', popularity: 'medium' },
  { hashtag: 'investing', topic: 'investing_stocks', popularity: 'high' },
  { hashtag: 'stocks', topic: 'investing_stocks', popularity: 'high' },
  { hashtag: 'stockmarket', topic: 'investing_stocks', popularity: 'high' },
  { hashtag: 'trading', topic: 'investing_stocks', popularity: 'high' },
  { hashtag: 'investor', topic: 'investing_stocks', popularity: 'medium' },
  { hashtag: 'finance', topic: 'investing_stocks', popularity: 'high' },
  { hashtag: 'portfolio', topic: 'investing_stocks', popularity: 'low' },
  { hashtag: 'dividends', topic: 'investing_stocks', popularity: 'low' },
  { hashtag: 'passiveincome', topic: 'investing_stocks', popularity: 'high' },
  { hashtag: 'personalfinance', topic: 'personal_finance', popularity: 'high' },
  { hashtag: 'moneytips', topic: 'personal_finance', popularity: 'medium' },
  { hashtag: 'budgeting', topic: 'personal_finance', popularity: 'medium' },
  { hashtag: 'saving', topic: 'personal_finance', popularity: 'medium' },
  { hashtag: 'debtfree', topic: 'personal_finance', popularity: 'high' },
  { hashtag: 'financialfreedom', topic: 'personal_finance', popularity: 'high' },
  { hashtag: 'fire', topic: 'personal_finance', popularity: 'medium' },
  { hashtag: 'frugal', topic: 'personal_finance', popularity: 'medium' },
  { hashtag: 'moneysaving', topic: 'personal_finance', popularity: 'medium' },
  { hashtag: 'career', topic: 'career_jobs', popularity: 'high' },
  { hashtag: 'jobs', topic: 'career_jobs', popularity: 'high' },
  { hashtag: 'hiring', topic: 'career_jobs', popularity: 'medium' },
  { hashtag: 'jobsearch', topic: 'career_jobs', popularity: 'medium' },
  { hashtag: 'careerdevelopment', topic: 'career_jobs', popularity: 'medium' },
  { hashtag: 'professionaldevelopment', topic: 'career_jobs', popularity: 'low' },
  { hashtag: 'worklife', topic: 'career_jobs', popularity: 'medium' },
  { hashtag: 'careeradvice', topic: 'career_jobs', popularity: 'low' },
  { hashtag: 'remotework', topic: 'career_jobs', popularity: 'high' },
  { hashtag: 'wfh', topic: 'career_jobs', popularity: 'high' },
  { hashtag: 'workfromhome', topic: 'career_jobs', popularity: 'high' },
  { hashtag: 'business', topic: 'entrepreneurship', popularity: 'high' },
  { hashtag: 'success', topic: 'entrepreneurship', popularity: 'high' },

  // Fashion & Beauty (50 hashtags)
  { hashtag: 'fashion', topic: 'fashion', popularity: 'high' },
  { hashtag: 'style', topic: 'fashion', popularity: 'high' },
  { hashtag: 'ootd', topic: 'fashion', popularity: 'high' },
  { hashtag: 'outfitoftheday', topic: 'fashion', popularity: 'high' },
  { hashtag: 'fashionblogger', topic: 'fashion', popularity: 'high' },
  { hashtag: 'fashionista', topic: 'fashion', popularity: 'high' },
  { hashtag: 'instafashion', topic: 'fashion', popularity: 'high' },
  { hashtag: 'streetstyle', topic: 'fashion', popularity: 'high' },
  { hashtag: 'fashionweek', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'stylish', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'fashiongram', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'fashionaddict', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'lookbook', topic: 'fashion', popularity: 'low' },
  { hashtag: 'fashioninspo', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'ootdfashion', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'beauty', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'skincare', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'makeup', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'beautyblogger', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'skincarerotine', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'beautytips', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'makeuptutorial', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'cosmetics', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'makeupartist', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'mua', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'makeuplover', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'makeupaddict', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'beautycommunity', topic: 'beauty_skincare', popularity: 'low' },
  { hashtag: 'skincareroutine', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'skincaretips', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'glowingskin', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'kbeauty', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'koreanbeauty', topic: 'beauty_skincare', popularity: 'low' },
  { hashtag: 'skincareaddict', topic: 'beauty_skincare', popularity: 'low' },
  { hashtag: 'selfcare', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'hair', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'hairstyle', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'haircare', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'nails', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'nailart', topic: 'beauty_skincare', popularity: 'high' },
  { hashtag: 'manicure', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'naildesign', topic: 'beauty_skincare', popularity: 'medium' },
  { hashtag: 'shoes', topic: 'fashion', popularity: 'high' },
  { hashtag: 'sneakers', topic: 'fashion', popularity: 'high' },
  { hashtag: 'sneakerhead', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'accessories', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'jewelry', topic: 'fashion', popularity: 'high' },
  { hashtag: 'watches', topic: 'fashion', popularity: 'medium' },
  { hashtag: 'luxury', topic: 'fashion', popularity: 'high' },
  { hashtag: 'designer', topic: 'fashion', popularity: 'medium' },

  // Food & Cooking (40 hashtags)
  { hashtag: 'food', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodie', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'cooking', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'recipe', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodporn', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'instafood', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodphotography', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'homecooking', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'baking', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'chef', topic: 'food_cooking', popularity: 'medium' },
  { hashtag: 'yum', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'delicious', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodstagram', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodblogger', topic: 'food_cooking', popularity: 'medium' },
  { hashtag: 'yummy', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'tasty', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodlover', topic: 'food_cooking', popularity: 'medium' },
  { hashtag: 'homemade', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'dinner', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'lunch', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'breakfast', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'dessert', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'pizza', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'pasta', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'sushi', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'burger', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'cake', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'chocolate', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'coffee', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'wine', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodgasm', topic: 'food_cooking', popularity: 'medium' },
  { hashtag: 'eats', topic: 'food_cooking', popularity: 'medium' },
  { hashtag: 'nom', topic: 'food_cooking', popularity: 'medium' },
  { hashtag: 'nomnom', topic: 'food_cooking', popularity: 'medium' },
  { hashtag: 'restaurant', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodcoma', topic: 'food_cooking', popularity: 'low' },
  { hashtag: 'foodies', topic: 'food_cooking', popularity: 'high' },
  { hashtag: 'foodoftheday', topic: 'food_cooking', popularity: 'medium' },
  { hashtag: 'healthyfood', topic: 'nutrition_diet', popularity: 'high' },
  { hashtag: 'veganfood', topic: 'nutrition_diet', popularity: 'high' },

  // Travel (30 hashtags)
  { hashtag: 'travel', topic: 'travel', popularity: 'high' },
  { hashtag: 'traveling', topic: 'travel', popularity: 'high' },
  { hashtag: 'vacation', topic: 'travel', popularity: 'high' },
  { hashtag: 'wanderlust', topic: 'travel', popularity: 'high' },
  { hashtag: 'instatravel', topic: 'travel', popularity: 'high' },
  { hashtag: 'travelgram', topic: 'travel', popularity: 'high' },
  { hashtag: 'adventure', topic: 'travel', popularity: 'high' },
  { hashtag: 'explore', topic: 'travel', popularity: 'high' },
  { hashtag: 'tourism', topic: 'travel', popularity: 'medium' },
  { hashtag: 'travelphotography', topic: 'travel', popularity: 'high' },
  { hashtag: 'traveltheworld', topic: 'travel', popularity: 'medium' },
  { hashtag: 'travelblogger', topic: 'travel', popularity: 'medium' },
  { hashtag: 'traveller', topic: 'travel', popularity: 'medium' },
  { hashtag: 'traveler', topic: 'travel', popularity: 'medium' },
  { hashtag: 'trip', topic: 'travel', popularity: 'high' },
  { hashtag: 'roadtrip', topic: 'travel', popularity: 'high' },
  { hashtag: 'beach', topic: 'travel', popularity: 'high' },
  { hashtag: 'mountains', topic: 'travel', popularity: 'high' },
  { hashtag: 'sunset', topic: 'travel', popularity: 'high' },
  { hashtag: 'holiday', topic: 'travel', popularity: 'high' },
  { hashtag: 'backpacking', topic: 'travel', popularity: 'medium' },
  { hashtag: 'backpacker', topic: 'travel', popularity: 'low' },
  { hashtag: 'worldtraveler', topic: 'travel', popularity: 'medium' },
  { hashtag: 'traveladdict', topic: 'travel', popularity: 'low' },
  { hashtag: 'travelholic', topic: 'travel', popularity: 'low' },
  { hashtag: 'passportready', topic: 'travel', popularity: 'low' },
  { hashtag: 'globetrotter', topic: 'travel', popularity: 'medium' },
  { hashtag: 'bucketlist', topic: 'travel', popularity: 'high' },
  { hashtag: 'beautifuldestinations', topic: 'travel', popularity: 'high' },
  { hashtag: 'getaway', topic: 'travel', popularity: 'medium' },

  // Entertainment (40 hashtags)
  { hashtag: 'movies', topic: 'movies_tv', popularity: 'high' },
  { hashtag: 'film', topic: 'movies_tv', popularity: 'high' },
  { hashtag: 'cinema', topic: 'movies_tv', popularity: 'medium' },
  { hashtag: 'tvshow', topic: 'movies_tv', popularity: 'medium' },
  { hashtag: 'netflix', topic: 'movies_tv', popularity: 'high' },
  { hashtag: 'streaming', topic: 'movies_tv', popularity: 'medium' },
  { hashtag: 'movienight', topic: 'movies_tv', popularity: 'high' },
  { hashtag: 'filmreview', topic: 'movies_tv', popularity: 'low' },
  { hashtag: 'hollywood', topic: 'movies_tv', popularity: 'high' },
  { hashtag: 'actor', topic: 'movies_tv', popularity: 'medium' },
  { hashtag: 'music', topic: 'music', popularity: 'high' },
  { hashtag: 'musician', topic: 'music', popularity: 'high' },
  { hashtag: 'song', topic: 'music', popularity: 'high' },
  { hashtag: 'artist', topic: 'music', popularity: 'high' },
  { hashtag: 'newmusic', topic: 'music', popularity: 'high' },
  { hashtag: 'musicvideo', topic: 'music', popularity: 'medium' },
  { hashtag: 'concert', topic: 'music', popularity: 'high' },
  { hashtag: 'spotify', topic: 'music', popularity: 'high' },
  { hashtag: 'playlist', topic: 'music', popularity: 'high' },
  { hashtag: 'musiclover', topic: 'music', popularity: 'high' },
  { hashtag: 'hiphop', topic: 'music', popularity: 'high' },
  { hashtag: 'rap', topic: 'music', popularity: 'high' },
  { hashtag: 'rock', topic: 'music', popularity: 'high' },
  { hashtag: 'pop', topic: 'music', popularity: 'high' },
  { hashtag: 'livemusic', topic: 'music', popularity: 'medium' },
  { hashtag: 'books', topic: 'books_reading', popularity: 'high' },
  { hashtag: 'reading', topic: 'books_reading', popularity: 'high' },
  { hashtag: 'bookstagram', topic: 'books_reading', popularity: 'high' },
  { hashtag: 'bookworm', topic: 'books_reading', popularity: 'high' },
  { hashtag: 'booklover', topic: 'books_reading', popularity: 'high' },
  { hashtag: 'bookclub', topic: 'books_reading', popularity: 'medium' },
  { hashtag: 'amreading', topic: 'books_reading', popularity: 'medium' },
  { hashtag: 'bookish', topic: 'books_reading', popularity: 'medium' },
  { hashtag: 'author', topic: 'books_reading', popularity: 'medium' },
  { hashtag: 'celebrity', topic: 'celebrities', popularity: 'high' },
  { hashtag: 'celeb', topic: 'celebrities', popularity: 'medium' },
  { hashtag: 'celebrities', topic: 'celebrities', popularity: 'high' },
  { hashtag: 'famous', topic: 'celebrities', popularity: 'medium' },
  { hashtag: 'entertainment', topic: 'celebrities', popularity: 'high' },
  { hashtag: 'gossip', topic: 'celebrities', popularity: 'medium' },

  // Sports (30 hashtags)
  { hashtag: 'sports', topic: 'sports_general', popularity: 'high' },
  { hashtag: 'athlete', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'championship', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'tournament', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'sportsnews', topic: 'sports_general', popularity: 'low' },
  { hashtag: 'football', topic: 'football_soccer', popularity: 'high' },
  { hashtag: 'soccer', topic: 'football_soccer', popularity: 'high' },
  { hashtag: 'nfl', topic: 'football_soccer', popularity: 'high' },
  { hashtag: 'premierleague', topic: 'football_soccer', popularity: 'high' },
  { hashtag: 'championsleague', topic: 'football_soccer', popularity: 'medium' },
  { hashtag: 'fifa', topic: 'football_soccer', popularity: 'high' },
  { hashtag: 'worldcup', topic: 'football_soccer', popularity: 'high' },
  { hashtag: 'footballseason', topic: 'football_soccer', popularity: 'medium' },
  { hashtag: 'basketball', topic: 'basketball', popularity: 'high' },
  { hashtag: 'nba', topic: 'basketball', popularity: 'high' },
  { hashtag: 'hoops', topic: 'basketball', popularity: 'medium' },
  { hashtag: 'nbabasketball', topic: 'basketball', popularity: 'medium' },
  { hashtag: 'basketballlife', topic: 'basketball', popularity: 'low' },
  { hashtag: 'playoffs', topic: 'basketball', popularity: 'medium' },
  { hashtag: 'baseball', topic: 'sports_general', popularity: 'high' },
  { hashtag: 'mlb', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'hockey', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'nhl', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'tennis', topic: 'sports_general', popularity: 'high' },
  { hashtag: 'golf', topic: 'sports_general', popularity: 'high' },
  { hashtag: 'mma', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'ufc', topic: 'sports_general', popularity: 'high' },
  { hashtag: 'boxing', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'olympics', topic: 'sports_general', popularity: 'medium' },
  { hashtag: 'race', topic: 'sports_general', popularity: 'medium' },

  // Parenting & Family (20 hashtags)
  { hashtag: 'parenting', topic: 'parenting', popularity: 'high' },
  { hashtag: 'parenthood', topic: 'parenting', popularity: 'medium' },
  { hashtag: 'mom', topic: 'parenting', popularity: 'high' },
  { hashtag: 'dad', topic: 'parenting', popularity: 'high' },
  { hashtag: 'momlife', topic: 'parenting', popularity: 'high' },
  { hashtag: 'dadlife', topic: 'parenting', popularity: 'high' },
  { hashtag: 'kids', topic: 'parenting', popularity: 'high' },
  { hashtag: 'baby', topic: 'parenting', popularity: 'high' },
  { hashtag: 'toddler', topic: 'parenting', popularity: 'high' },
  { hashtag: 'family', topic: 'parenting', popularity: 'high' },
  { hashtag: 'motherhood', topic: 'parenting', popularity: 'high' },
  { hashtag: 'fatherhood', topic: 'parenting', popularity: 'medium' },
  { hashtag: 'momsofinstagram', topic: 'parenting', popularity: 'high' },
  { hashtag: 'dadsofinstagram', topic: 'parenting', popularity: 'medium' },
  { hashtag: 'babylove', topic: 'parenting', popularity: 'medium' },
  { hashtag: 'pregnant', topic: 'parenting', popularity: 'high' },
  { hashtag: 'pregnancy', topic: 'parenting', popularity: 'high' },
  { hashtag: 'newborn', topic: 'parenting', popularity: 'high' },
  { hashtag: 'familytime', topic: 'parenting', popularity: 'high' },
  { hashtag: 'parentingtips', topic: 'parenting', popularity: 'low' },

  // Lifestyle & Hobbies (30 hashtags)
  { hashtag: 'photography', topic: 'photography', popularity: 'high' },
  { hashtag: 'photo', topic: 'photography', popularity: 'high' },
  { hashtag: 'photographer', topic: 'photography', popularity: 'high' },
  { hashtag: 'photooftheday', topic: 'photography', popularity: 'high' },
  { hashtag: 'picoftheday', topic: 'photography', popularity: 'high' },
  { hashtag: 'art', topic: 'art_design', popularity: 'high' },
  { hashtag: 'artist', topic: 'art_design', popularity: 'high' },
  { hashtag: 'artwork', topic: 'art_design', popularity: 'high' },
  { hashtag: 'design', topic: 'art_design', popularity: 'high' },
  { hashtag: 'creative', topic: 'art_design', popularity: 'high' },
  { hashtag: 'drawing', topic: 'art_design', popularity: 'high' },
  { hashtag: 'painting', topic: 'art_design', popularity: 'high' },
  { hashtag: 'illustration', topic: 'art_design', popularity: 'high' },
  { hashtag: 'graphicdesign', topic: 'art_design', popularity: 'high' },
  { hashtag: 'artistsoninstagram', topic: 'art_design', popularity: 'high' },
  { hashtag: 'diy', topic: 'diy_crafts', popularity: 'high' },
  { hashtag: 'crafts', topic: 'diy_crafts', popularity: 'high' },
  { hashtag: 'handmade', topic: 'diy_crafts', popularity: 'high' },
  { hashtag: 'crafting', topic: 'diy_crafts', popularity: 'medium' },
  { hashtag: 'diyproject', topic: 'diy_crafts', popularity: 'medium' },
  { hashtag: 'homedecor', topic: 'home_decor', popularity: 'high' },
  { hashtag: 'interiordesign', topic: 'home_decor', popularity: 'high' },
  { hashtag: 'homedesign', topic: 'home_decor', popularity: 'high' },
  { hashtag: 'pets', topic: 'pets', popularity: 'high' },
  { hashtag: 'dog', topic: 'pets', popularity: 'high' },
  { hashtag: 'cat', topic: 'pets', popularity: 'high' },
  { hashtag: 'dogsofinstagram', topic: 'pets', popularity: 'high' },
  { hashtag: 'catsofinstagram', topic: 'pets', popularity: 'high' },
  { hashtag: 'puppy', topic: 'pets', popularity: 'high' },
  { hashtag: 'kitten', topic: 'pets', popularity: 'high' },

  // Other (20 hashtags)
  { hashtag: 'news', topic: 'news_current_events', popularity: 'high' },
  { hashtag: 'breakingnews', topic: 'news_current_events', popularity: 'medium' },
  { hashtag: 'politics', topic: 'politics', popularity: 'high' },
  { hashtag: 'education', topic: 'education', popularity: 'high' },
  { hashtag: 'science', topic: 'science', popularity: 'high' },
  { hashtag: 'climatechange', topic: 'climate_environment', popularity: 'high' },
  { hashtag: 'environment', topic: 'climate_environment', popularity: 'high' },
  { hashtag: 'sustainability', topic: 'climate_environment', popularity: 'high' },
  { hashtag: 'nature', topic: 'nature_wildlife', popularity: 'high' },
  { hashtag: 'wildlife', topic: 'nature_wildlife', popularity: 'high' },
  { hashtag: 'cars', topic: 'cars_automotive', popularity: 'high' },
  { hashtag: 'automotive', topic: 'cars_automotive', popularity: 'medium' },
  { hashtag: 'relationship', topic: 'relationships_dating', popularity: 'high' },
  { hashtag: 'love', topic: 'relationships_dating', popularity: 'high' },
  { hashtag: 'dating', topic: 'relationships_dating', popularity: 'high' },
  { hashtag: 'socialjustice', topic: 'social_justice', popularity: 'medium' },
  { hashtag: 'spirituality', topic: 'spirituality', popularity: 'medium' },
  { hashtag: 'motivation', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'inspiration', topic: 'mental_health', popularity: 'high' },
  { hashtag: 'positivevibes', topic: 'mental_health', popularity: 'high' }
];

/**
 * Build fast lookup map from hashtag to topic
 * @returns Map of lowercase hashtags (without #) to topic names
 */
export function buildHashtagLookup(): Map<string, string> {
  const lookup = new Map<string, string>();

  for (const mapping of HASHTAG_MAPPINGS) {
    lookup.set(mapping.hashtag.toLowerCase(), mapping.topic);
  }

  return lookup;
}

/**
 * Get topic from hashtag
 * @param hashtag - Hashtag with or without # prefix
 * @returns Topic name or undefined
 */
export function getTopicFromHashtag(hashtag: string): string | undefined {
  const clean = hashtag.toLowerCase().replace(/^#/, '');
  const lookup = buildHashtagLookup();
  return lookup.get(clean);
}

/**
 * Get topics from multiple hashtags
 * @param hashtags - Array of hashtags
 * @returns Array of unique topic names
 */
export function getTopicsFromHashtags(hashtags: string[]): string[] {
  const topics = new Set<string>();
  const lookup = buildHashtagLookup();

  for (const hashtag of hashtags) {
    const clean = hashtag.toLowerCase().replace(/^#/, '');
    const topic = lookup.get(clean);
    if (topic) {
      topics.add(topic);
    }
  }

  return Array.from(topics);
}
