/**
 * AI Visual Signals Detection Module
 *
 * Detects signals consistent with AI-generated visual content in feed items.
 *
 * CRITICAL HONESTY RULE:
 * - We detect "signals consistent with AI generation", NOT certainty
 * - Default behavior is CONSERVATIVE: if unsure, return NO_STRONG_SIGNALS
 * - Never guess or speculate
 *
 * Signal sources (in order of reliability):
 * 1. C2PA / Content Credentials (explicit AI generation metadata)
 * 2. Platform AI labels (Instagram/TikTok/X explicit AI tags)
 * 3. EXIF metadata with AI tool signatures
 * 4. (Future) Visual analysis if bytes available
 *
 * DO NOT:
 * - Fetch remote media URLs (privacy + CORS issues)
 * - Attempt visual analysis without explicit opt-in
 * - Make assumptions based on style or aesthetics
 */

/**
 * Compute AI visual signals for a single feed item
 *
 * @param {Object} item - Feed item from scan
 * @param {Object} options - Configuration options
 * @param {boolean} options.enableVisualAnalysis - Enable pixel-based analysis (default: false)
 * @returns {Object} { label: 'LIKELY_AI' | 'POSSIBLY_AI' | 'NO_STRONG_SIGNALS', signals: [], confidence: string, reason: string }
 */
export function computeAiVisualSignalsForItem(item, options = {}) {
  const { enableVisualAnalysis = false } = options;

  const result = {
    label: 'NO_STRONG_SIGNALS',
    signals: [],
    confidence: 'LOW',
    reason: null,
  };

  // Check if item has visual content
  const mediaType = item.media_type || item.content_type || item.type;
  const isVisual = mediaType === 'image' || mediaType === 'video';

  if (!isVisual) {
    result.reason = 'not_visual_content';
    return result;
  }

  // Check if media bytes or thumbnail available
  const hasMediaData = item.media_bytes || item.thumbnail_bytes || item.image_url || item.video_url;
  if (!hasMediaData) {
    result.reason = 'no_media_available';
    return result;
  }

  // SIGNAL 1: C2PA / Content Credentials (HIGHEST CONFIDENCE)
  // C2PA is an open standard for content provenance and authenticity
  if (item.c2pa_manifest || item.content_credentials) {
    const manifest = item.c2pa_manifest || item.content_credentials;

    // Check for AI generation assertions
    if (manifest.assertions) {
      const aiAssertion = manifest.assertions.find(
        (a) => a.label === 'c2pa.ai_generative' || a.label === 'stds.schema-org.CreativeWork'
      );

      if (aiAssertion) {
        result.label = 'LIKELY_AI';
        result.signals.push('c2pa_ai_generation');
        result.confidence = 'HIGH';
        result.reason = 'c2pa_manifest_with_ai_assertion';
        return result;
      }
    }

    // C2PA exists but no AI assertion - slightly increases confidence
    result.signals.push('c2pa_manifest_present');
  }

  // SIGNAL 2: Platform AI Labels (HIGH CONFIDENCE)
  // Instagram, TikTok, X, etc. may add explicit AI labels
  if (item.platform_labels || item.content_labels || item.labels) {
    const labels = item.platform_labels || item.content_labels || item.labels;
    const labelArray = Array.isArray(labels) ? labels : [labels];

    // Check for explicit AI labels
    const hasAiLabel = labelArray.some((label) => {
      const labelStr = typeof label === 'string' ? label.toLowerCase() : label?.text?.toLowerCase() || '';
      return (
        labelStr.includes('ai generated') ||
        labelStr.includes('ai-generated') ||
        labelStr.includes('made with ai') ||
        labelStr.includes('created with ai') ||
        labelStr.includes('generated by ai')
      );
    });

    if (hasAiLabel) {
      result.label = 'LIKELY_AI';
      result.signals.push('platform_ai_label');
      result.confidence = 'HIGH';
      result.reason = 'explicit_platform_ai_label';
      return result;
    }
  }

  // SIGNAL 3: EXIF Metadata with AI Tool Signatures (MEDIUM CONFIDENCE)
  if (item.exif_metadata || item.metadata) {
    const exif = item.exif_metadata || item.metadata;

    // Check for known AI tool signatures in EXIF
    const softwareField = exif.Software || exif.software || exif.CreatorTool || '';
    const aiTools = [
      'midjourney',
      'dall-e',
      'dalle',
      'stable diffusion',
      'stablediffusion',
      'firefly',
      'adobe firefly',
      'generative fill',
      'ai generator',
      'dreamstudio',
      'runway',
      'synthesia',
    ];

    const hasAiToolSignature = aiTools.some((tool) => softwareField.toLowerCase().includes(tool));

    if (hasAiToolSignature) {
      result.label = 'LIKELY_AI';
      result.signals.push('exif_ai_tool');
      result.confidence = 'MEDIUM';
      result.reason = 'exif_metadata_contains_ai_tool';
      return result;
    }

    // Check for EXIF fields that suggest manipulation (weaker signal)
    const hasManipulationMarkers =
      exif.ProcessingSoftware ||
      exif['Photoshop:History'] ||
      exif.SerialNumber === 'SYNTHETIC' ||
      exif.Make === 'AI';

    if (hasManipulationMarkers) {
      result.signals.push('exif_manipulation_markers');
    }
  }

  // SIGNAL 4: Visual Analysis (ONLY if explicitly enabled and media bytes available)
  // This is NOT implemented yet - placeholder for future enhancement
  if (enableVisualAnalysis && (item.media_bytes || item.thumbnail_bytes)) {
    // Future: implement pixel-based heuristics
    // - Check for unnatural smoothness in skin tones
    // - Check for impossible lighting consistency
    // - Check for anatomical inconsistencies
    // - Check for JPEG artifacts vs. synthetic patterns
    //
    // For now, this is NOT ENABLED to avoid false positives
    result.signals.push('visual_analysis_not_yet_implemented');
  }

  // FINAL: If we found multiple weak signals, upgrade to POSSIBLY_AI
  if (result.signals.length >= 2) {
    result.label = 'POSSIBLY_AI';
    result.confidence = 'LOW';
    result.reason = 'multiple_weak_signals';
    return result;
  }

  // Default: NO_STRONG_SIGNALS
  if (result.signals.length > 0) {
    result.reason = 'weak_signals_insufficient';
  } else {
    result.reason = 'no_signals_detected';
  }

  return result;
}

/**
 * Batch compute AI visual signals for multiple feed items
 *
 * @param {Array} items - Array of feed items
 * @param {Object} options - Configuration options
 * @returns {Array} Array of results matching input order
 */
export function computeAiVisualSignalsForBatch(items, options = {}) {
  return items.map((item) => computeAiVisualSignalsForItem(item, options));
}

/**
 * Enrich feed items with aiVisualSignals field (mutates in place)
 *
 * This is the function that should be called when processing scan results
 * to add the aiVisualSignals field to each feed item.
 *
 * @param {Array} feedItems - Feed items from scan result
 * @param {Object} options - Configuration options
 * @returns {Array} Same feed items array (mutated with aiVisualSignals field)
 */
export function enrichFeedItemsWithAiSignals(feedItems, options = {}) {
  if (!Array.isArray(feedItems)) {
    return feedItems;
  }

  for (const item of feedItems) {
    const result = computeAiVisualSignalsForItem(item, options);
    item.aiVisualSignals = result.label;

    // Optionally store detailed signals for debugging
    if (options.includeSignalDetails) {
      item.aiVisualSignalsDetail = {
        signals: result.signals,
        confidence: result.confidence,
        reason: result.reason,
      };
    }
  }

  return feedItems;
}

/**
 * Export constants for testing
 */
export const AI_SIGNAL_LABELS = {
  LIKELY_AI: 'LIKELY_AI',
  POSSIBLY_AI: 'POSSIBLY_AI',
  NO_STRONG_SIGNALS: 'NO_STRONG_SIGNALS',
};

export const CONFIDENCE_LEVELS = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};
