/**
 * Real-scan fixtures for the interpretation engine smoke test
 * (Phase 4.5.1a).
 *
 * Source: two real YouTube scans from production Supabase, exported
 * on 2026-05-16. PII redacted:
 *   - creator_handle:        "@<real>"        → "@creator-N"
 *   - creator_display_name:  "<real name>"    → "Creator N"
 *   - post_text:             "<real caption>" → ""
 *   - user_id:                                → "user-fixture"
 *
 * Handle ordinals are stable across both scans: the same real creator
 * maps to the same @creator-N in REAL_ACTIVE_SCAN and REAL_PRIOR_SCAN.
 * This preserves cross-scan recurrence patterns that the engine reads
 * (via raw_data.posts grouped by handle for top-creator share).
 *
 * Non-PII fields preserved verbatim:
 *   - id, scan_id (if present), platform, created_at
 *   - post_count, ad_count, ad_percentage,
 *     suggested_count, suggested_percentage
 *   - is_ad, is_suggested, content_type, hashtags, position_in_feed,
 *     ad_label_text on every post
 *   - political.is_political, emotions.valence on every analyzed item
 *
 * Generated by /redact-fixture.js (deleted after fixture creation).
 * Do not regenerate by hand — re-run the script with a fresh
 * fixture-source.csv if the underlying scans need to change.
 */

import type { ScanDetail } from '../../../../hooks/useDashboard';

export const REAL_ACTIVE_SCAN: ScanDetail = {
  "id": "8230a0b2-4bed-4270-a3d4-87028d484098",
  "user_id": "user-fixture",
  "ad_count": 1,
  "platform": "youtube",
  "raw_data": {
    "posts": [
      {
        "is_ad": true,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": true,
        "ad_label_text": "Ad",
        "creator_handle": "@creator-1",
        "position_in_feed": 1,
        "creator_display_name": "Creator 1"
      },
      {
        "is_ad": false,
        "hashtags": [
          "#shorts",
          "#teenmom",
          "#tlcunexpected"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 2,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#shorts",
          "#americanpie",
          "#ytshorts"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 3,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#shorts",
          "#funny",
          "#sora2",
          "#viral"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 4,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 5,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-2",
        "position_in_feed": 6,
        "creator_display_name": "Creator 2"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-3",
        "position_in_feed": 7,
        "creator_display_name": "Creator 3"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 8,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 9,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 10,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#entourage",
          "#movie"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 11,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#233"
        ],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-4",
        "position_in_feed": 12,
        "creator_display_name": "Creator 4"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-5",
        "position_in_feed": 13,
        "creator_display_name": "Creator 5"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-6",
        "position_in_feed": 14,
        "creator_display_name": "Creator 6"
      },
      {
        "is_ad": false,
        "hashtags": [
          "#67"
        ],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-7",
        "position_in_feed": 15,
        "creator_display_name": "Creator 7"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-8",
        "position_in_feed": 16,
        "creator_display_name": "Creator 8"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-9",
        "position_in_feed": 17,
        "creator_display_name": "Creator 9"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-10",
        "position_in_feed": 18,
        "creator_display_name": "Creator 10"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-11",
        "position_in_feed": 19,
        "creator_display_name": "Creator 11"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-12",
        "position_in_feed": 20,
        "creator_display_name": "Creator 12"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 21,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 22,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#shortsviral"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 23,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#shorts"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 24,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-13",
        "position_in_feed": 25,
        "creator_display_name": "Creator 13"
      },
      {
        "is_ad": false,
        "hashtags": [
          "#modernfamily",
          "#funny",
          "#shorts"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 26,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#yosho"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 27,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#KimKardashian",
          "#Kardashians"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 28,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#ranking",
          "#mom",
          "#funny",
          "#trend",
          "#reelschallenge"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 29,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-14",
        "position_in_feed": 30,
        "creator_display_name": "Creator 14"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-15",
        "position_in_feed": 31,
        "creator_display_name": "Creator 15"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-16",
        "position_in_feed": 32,
        "creator_display_name": "Creator 16"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-13",
        "position_in_feed": 33,
        "creator_display_name": "Creator 13"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-17",
        "position_in_feed": 34,
        "creator_display_name": "Creator 17"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-18",
        "position_in_feed": 35,
        "creator_display_name": "Creator 18"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-19",
        "position_in_feed": 36,
        "creator_display_name": "Creator 19"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-20",
        "position_in_feed": 37,
        "creator_display_name": "Creator 20"
      }
    ],
    "scanned_at": "2026-02-27T12:52:44.181Z",
    "top_creators": [
      {
        "0": "u",
        "1": "n",
        "2": "k",
        "3": "n",
        "4": "o",
        "5": "w",
        "6": "n"
      },
      {
        "0": "T",
        "1": "h",
        "2": "e",
        "3": "O",
        "4": "f",
        "5": "f",
        "6": "i",
        "7": "c",
        "8": "e"
      },
      {
        "0": "G",
        "1": "o",
        "2": "o",
        "3": "g",
        "4": "l",
        "5": "e"
      },
      {
        "0": "C",
        "1": "o",
        "2": "m",
        "3": "e",
        "4": "d",
        "5": "y",
        "6": "B",
        "7": "i",
        "8": "t",
        "9": "e",
        "10": "s"
      },
      {
        "0": "F",
        "1": "o",
        "2": "x",
        "3": "N",
        "4": "e",
        "5": "w",
        "6": "s"
      },
      {
        "0": "D",
        "1": "e",
        "2": "e",
        "3": "p",
        "4": "R",
        "5": "a",
        "6": "d",
        "7": "i",
        "8": "o",
        "9": "1",
        "10": "1",
        "11": "2"
      },
      {
        "0": "m",
        "1": "i",
        "2": "n",
        "3": "d",
        "4": "_",
        "5": "w",
        "6": "a",
        "7": "r",
        "8": "e",
        "9": "h",
        "10": "o",
        "11": "u",
        "12": "s",
        "13": "e"
      },
      {
        "0": "S",
        "1": "B",
        "2": "M",
        "3": "o",
        "4": "w",
        "5": "i",
        "6": "n",
        "7": "g"
      },
      {
        "0": "I",
        "1": "r",
        "2": "o",
        "3": "n",
        "4": "A",
        "5": "g",
        "6": "e",
        "7": "-",
        "8": "r",
        "9": "8",
        "10": "t"
      },
      {
        "0": "D",
        "1": "o",
        "2": "c",
        "3": "t",
        "4": "o",
        "5": "r",
        "6": "M",
        "7": "i",
        "8": "k",
        "9": "e"
      }
    ],
    "duration_seconds": 62
  },
  "created_at": "2026-02-27T12:52:44.187+00:00",
  "post_count": 37,
  "ad_percentage": 3,
  "suggested_count": 37,
  "suggested_percentage": 100
};

export const REAL_PRIOR_SCAN: ScanDetail = {
  "id": "252b9718-9ed8-4d30-9c22-92c1a4ed58d2",
  "user_id": "user-fixture",
  "ad_count": 2,
  "platform": "youtube",
  "raw_data": {
    "posts": [
      {
        "is_ad": true,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": true,
        "ad_label_text": "Ad",
        "creator_handle": "@creator-1",
        "position_in_feed": 1,
        "creator_display_name": "Creator 1"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-13",
        "position_in_feed": 2,
        "creator_display_name": "Creator 13"
      },
      {
        "is_ad": false,
        "hashtags": [
          "#anatoly",
          "#gym",
          "#prank",
          "#ytshorts"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 3,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#husbandwife",
          "#relationship",
          "#austenalexander"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 4,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 5,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#shorts"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 6,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-21",
        "position_in_feed": 7,
        "creator_display_name": "Creator 21"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-22",
        "position_in_feed": 8,
        "creator_display_name": "Creator 22"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 9,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#golf",
          "#golfswing",
          "#golfing"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 10,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 11,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [
          "#youtubeshorts",
          "#youtubeviral",
          "#fitness"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 12,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-23",
        "position_in_feed": 13,
        "creator_display_name": "Creator 23"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-24",
        "position_in_feed": 14,
        "creator_display_name": "Creator 24"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-13",
        "position_in_feed": 15,
        "creator_display_name": "Creator 13"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-25",
        "position_in_feed": 16,
        "creator_display_name": "Creator 25"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-26",
        "position_in_feed": 17,
        "creator_display_name": "Creator 26"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-27",
        "position_in_feed": 18,
        "creator_display_name": "Creator 27"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-28",
        "position_in_feed": 19,
        "creator_display_name": "Creator 28"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-29",
        "position_in_feed": 20,
        "creator_display_name": "Creator 29"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-30",
        "position_in_feed": 21,
        "creator_display_name": "Creator 30"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-31",
        "position_in_feed": 22,
        "creator_display_name": "Creator 31"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-2",
        "position_in_feed": 23,
        "creator_display_name": "Creator 2"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-2",
        "position_in_feed": 24,
        "creator_display_name": "Creator 2"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-13",
        "position_in_feed": 25,
        "creator_display_name": "Creator 13"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-32",
        "position_in_feed": 26,
        "creator_display_name": "Creator 32"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-18",
        "position_in_feed": 27,
        "creator_display_name": "Creator 18"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-33",
        "position_in_feed": 28,
        "creator_display_name": "Creator 33"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-34",
        "position_in_feed": 29,
        "creator_display_name": "Creator 34"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-35",
        "position_in_feed": 30,
        "creator_display_name": "Creator 35"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-36",
        "position_in_feed": 31,
        "creator_display_name": "Creator 36"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-3",
        "position_in_feed": 32,
        "creator_display_name": "Creator 3"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-37",
        "position_in_feed": 33,
        "creator_display_name": "Creator 37"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-38",
        "position_in_feed": 34,
        "creator_display_name": "Creator 38"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-39",
        "position_in_feed": 35,
        "creator_display_name": "Creator 39"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-40",
        "position_in_feed": 36,
        "creator_display_name": "Creator 40"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-41",
        "position_in_feed": 37,
        "creator_display_name": "Creator 41"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-42",
        "position_in_feed": 38,
        "creator_display_name": "Creator 42"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-43",
        "position_in_feed": 39,
        "creator_display_name": "Creator 43"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-44",
        "position_in_feed": 40,
        "creator_display_name": "Creator 44"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-45",
        "position_in_feed": 41,
        "creator_display_name": "Creator 45"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-46",
        "position_in_feed": 42,
        "creator_display_name": "Creator 46"
      },
      {
        "is_ad": true,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": true,
        "ad_label_text": "Ad",
        "creator_handle": "@creator-47",
        "position_in_feed": 43,
        "creator_display_name": "Creator 47"
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-13",
        "position_in_feed": 44,
        "creator_display_name": "Creator 13"
      },
      {
        "is_ad": false,
        "hashtags": [
          "#shorts"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 45,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 46,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-48",
        "position_in_feed": 47,
        "creator_display_name": "Creator 48"
      },
      {
        "is_ad": false,
        "hashtags": [
          "#ranking",
          "#brooke",
          "#trend",
          "#shorts"
        ],
        "post_text": "",
        "content_type": "short",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": null,
        "position_in_feed": 48,
        "creator_display_name": null
      },
      {
        "is_ad": false,
        "hashtags": [],
        "post_text": "",
        "content_type": "video",
        "is_suggested": null,
        "ad_label_text": null,
        "creator_handle": "@creator-49",
        "position_in_feed": 49,
        "creator_display_name": "Creator 49"
      }
    ],
    "scanned_at": "2026-02-26T15:03:29.701Z",
    "top_creators": [
      {
        "0": "u",
        "1": "n",
        "2": "k",
        "3": "n",
        "4": "o",
        "5": "w",
        "6": "n"
      },
      {
        "0": "T",
        "1": "h",
        "2": "e",
        "3": "O",
        "4": "f",
        "5": "f",
        "6": "i",
        "7": "c",
        "8": "e"
      },
      {
        "0": "C",
        "1": "o",
        "2": "m",
        "3": "e",
        "4": "d",
        "5": "y",
        "6": "B",
        "7": "i",
        "8": "t",
        "9": "e",
        "10": "s"
      },
      {
        "0": "G",
        "1": "o",
        "2": "o",
        "3": "g",
        "4": "l",
        "5": "e"
      },
      {
        "0": "B",
        "1": "u",
        "2": "s",
        "3": "i",
        "4": "n",
        "5": "e",
        "6": "s",
        "7": "s",
        "8": "I",
        "9": "n",
        "10": "s",
        "11": "i",
        "12": "d",
        "13": "e",
        "14": "r"
      },
      {
        "0": "B",
        "1": "i",
        "2": "g",
        "3": "B",
        "4": "r",
        "5": "a",
        "6": "i",
        "7": "n",
        "8": "E",
        "9": "x",
        "10": "p",
        "11": "l",
        "12": "a",
        "13": "i",
        "14": "n",
        "15": "s"
      },
      {
        "0": "M",
        "1": "i",
        "2": "d",
        "3": "w",
        "4": "e",
        "5": "s",
        "6": "t",
        "7": "S",
        "8": "a",
        "9": "f",
        "10": "e",
        "11": "t",
        "12": "y"
      },
      {
        "0": "H",
        "1": "I",
        "2": "S",
        "3": "T",
        "4": "O",
        "5": "R",
        "6": "Y"
      },
      {
        "0": "N",
        "1": "F",
        "2": "L",
        "3": "F",
        "4": "i",
        "5": "l",
        "6": "m",
        "7": "s"
      },
      {
        "0": "W",
        "1": "a",
        "2": "r",
        "3": "n",
        "4": "e",
        "5": "r",
        "6": "B",
        "7": "r",
        "8": "o",
        "9": "s"
      }
    ],
    "duration_seconds": 70
  },
  "created_at": "2026-02-26T15:03:29.709+00:00",
  "post_count": 49,
  "ad_percentage": 4,
  "suggested_count": 49,
  "suggested_percentage": 100
};
